# Generated by Django 3.0.4 on 2020-12-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='site_admin',
        ),
        migrations.AlterModelTable(
            name='site_admin',
            table='site_admin',
        ),
    ]
